settings:
    running: 1
    revert_penalty: 350
    webserver_ip: 10.1.0.5
    polling:
        interval: 30
        jitter: 5

web_users:
    admin: TripleWater
    redteam: SunClose

teams:
    Team1:
        team_num: 1
        user:
            username: team1
            password: FalseThreat
    Team2:
        team_num: 2
        user:
            username: team2
            password: WeaponReady

vapps:
    Mock6_Local:
        subnet: "10.20.{}.0"
        netmask: 255.255.255.0
        systems:
            DC01:
                host: 10
                checks:
                    DC01-ldap:
                        type: ldap
                        port: 389
                        checker: match_ldap_output
                        ios:
                            dc01-ldap:
                                input:
                                    base: cn=Users,dc=REALFAKENEWS,dc=NET
                                    filter: (sAMAccountName=pete.merrill)
                                    attributes: [objectGUID]
                                output:
                                    objectGUID: [mKE1LEJ7jESXEyETKW8Zww==]



    Mock6_Remote:
        subnet: "10.0.{}.0"
        netmask: 255.255.255.0
        systems:

            FILES:
                host: 15
                checks:
                    FILES-ftp:
                        type: ftp
                        port: 21
                        checker: hash_match
                        ios:
                            files-ftp:
                                input:
                                    filepath: bundle/main.js
                                output:
                                    hash: "1e33bfdb375972088e7bf8f8df19fbce2aa16c4c"
                    FILES-ssh:
                        type: ssh
                        port: 22
                        checker: output_check
                        ios:
                            files-ssh:
                                input:
                                    task: ls -d /srv/ftp
                                output: 
                                    output: /srv/ftp


credentials:
    default_password: Password1!
    local:
        celeste.nichols:
            ios: ['files-ssh']
        shelby.melendez:
            ios: ['files-ftp']
        monique.reynolds:
            ios: ['files-ssh']

       
    domain:
        REALFAKENEWS.NET:
            myra.gardner:
                ios: ['dc01-ldap']
            joel.boone:
                ios: ['dc01-ldap']
            gloria.morales:
                ios: ['dc01-ldap']
           
